### ISSUE TITLE
The value of "messageid" could not be found from the original message

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/p5-Sisimai#151]
Reported at Pull-Request #150 , The following email has folded Message-Id field but Sisimai cannot get the value.
https://github.com/azumakuniyuki/p5-Sisimai/blob/master/eg/cannot-parse-yet/no-message-id.txt

```json
[
  {
    "token": "d158c8c23a469026ca008feb7175017f88dee6cf",
    "alias": "nobody@sample.co.jp",
    "lhost": "sample.net",
    "recipient": "nobody@sample.co.jp",
    "action": "failed",
    "softbounce": 0,
    "replycode": "550",
    "rhost": "smtp.sample.co.jp",
    "deliverystatus": "5.1.1",
    "diagnostictype": "SMTP",
    "timestamp": 1450778633,
    "smtpcommand": "RCPT",
    "addresser": "no-reply@sample.net",
    "diagnosticcode": "550 5.1.1 <nobody@sample.co.jp>: Recipient address rejected: User unknown in virtual mailbox table",
    "subject": "Test",
    "destination": "sample.co.jp",
    "smtpagent": "Postfix",
    "messageid": "",
    "feedbacktype": "",
    "reason": "userunknown",
    "senderdomain": "sample.net",
    "listid": "",
    "timezoneoffset": "+0900"
  }
]
```

**Comment by azumakuniyuki** [comment]
The email file has been move from eg/cannot-parse-yet to eg/something-is-wrong directory to avoid failure of make test.
https://github.com/azumakuniyuki/p5-Sisimai/blob/master/eg/something-is-wrong/no-message-id-from-pr-150.eml

**Comment by 0xcdcdcdcd** [comment]
I have tried to make a patch.
Please evaluate this.

[patch-151.zip](https://github.com/sisimai/p5-Sisimai/files/79553/patch-151.zip)

**Comment by azumakuniyuki** [comment]
@0xcdcdcdcd Thanks for the patch. I've applied the patch to new branch "patch-from-0xcdcdcdcd-for-issue-151" at issue #157
