### ISSUE TITLE
Not quoting $e->{'diagnosis'} before passing to qr

### ISSUE THREAD

**Issue by dzolnierz** [sisimai/p5-Sisimai#179]
We're using Sisimai v4.15.0 in our internal tool to catch bouncing addresses and we've found that when remote MTA (Exim) bounces email with reason like this:

Diagnostic-Code: smtp; 550 Bad SPF records for
    [newsletter-hub.com:77.55.92.138], see http://spf.pobox.com/

Our tool ends up with error:

Mar 13 15:30:55 bouncer5 bounceparser: Invalid [] range "r-h" in regex; marked by <-- HERE in m/550 Bad SPF records for [newsletter-h <-- HERE ub.com:212.182.125.16], see http://spf.pobox.com// at /usr/local/share/perl/5.20.2/Sisimai/MTA/Exim.pm line 404.

The line is:
my $rxdiagnosis = qr/$e->{'diagnosis'}/i;

The problem lies in treating r-h string in newsletter-hub.com domain like regex range. I think quoting $e->{'diagnosis'} before passing should help:

my $rxdiagnosis = qr/\Q$e->{'diagnosis'}\E/i;

But I am not sure this change would break something else.

**Comment by azumakuniyuki** [comment]
@dzolnierz Thanks for the bug report. 
I've got the error message when parsing the following bounce message using Sisimai 4.17.0:
```
Status: 5.0.0
Remote-MTA: dns; 127.0.0.1
Diagnostic-Code: smtp; 550 Bad SPF records for [newsletter-hub.com:77.55.92.138], see http://spf.pobox.com/
```
```shell
% perl -MSisimai -lE 'print Sisimai->dump(shift)' ./exim-28.eml
Invalid [] range "r-h" in regex; marked by <-- HERE in m/550 Bad SPF records for [newsletter-h <-- HERE ub.com:77.55.92.138], see http://spf.pobox.com// at /usr/local/lib/perl5/site_perl/5.22.1/Sisimai/MTA/Exim.pm line 387, <GEN0> line 53.
```

I'll try to fix the bug from tonight.

**Comment by dzolnierz** [comment]
Thanks, I look forward to seeing the fix.

**Comment by dzolnierz** [comment]
We have updated Sisiami to version 4.17.0p1 and all messages parsed smoothly. Many thanks.

**Comment by azumakuniyuki** [comment]
@dzolnierz Good news ! Thank you again for the bug report. This issue will be closed after the porting to the Ruby version of Sisimai.
