### ISSUE TITLE
softbounce detection

### ISSUE THREAD

**Issue by Quickeneen** [sisimai/p5-Sisimai#189]
"diagnosticcode": "550 5.2.0 Mail rejete. Mail rejected. ofr_506 [506]",
    "softbounce": 0,
    "rhost": "smtp-in.orange.fr",
    "destination": "orange.fr",

this softbounce is not an Hardbounce but a softbounce. this french ESP consider that the sender sent spam and has been blocked by orange Abuse team.

**Comment by azumakuniyuki** [comment]
Thanks for the report. 

As of present, the value of "softbounce" is just generated by the value of "diagnosticcode" or "replycode" at the following code:
https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai/SMTP.pm#L18-L66

* softbounce = 1 (diagnositiccode or replycode begins with "4" like "4.7.7", "4.2.2")
* softbounce = 0 (diagnositiccode or replycode begins with "5" like "5.1.1", "5.7.0")
* softbounce = -1 (diagnosticcode and replaycode are empty or neither 4 nor 5, such as "2.0.0")

Sisimai believes SMTP status code or D.S.N. status code generated at a local or a remote MTA. However, we sometimes receive an email bounce which reason is "mailboxfull" and status is "5.2.2. I'll try to improve codes related to "softbounce".

Thank you, again.

**Comment by Quickeneen** [comment]
ok i understand. 
I usually use a ponderation method between responsecode and the diagnostic content to determine which is the real softbounce status.  
hotmail, gmail and yahoo also are not using the correct responseCode about Blocked, unfortunately i have a bunch of examples :(
If i have time, i will try to fork something for you. 

Regards,

**Comment by azumakuniyuki** [comment]
I have tried to implement Sisimai::SMTP::Error->soft_or_hard() method for deciding that a bounce is a soft bounce or a hard bounce.

# The value of "softbounce"
1. "softbounce" is -1 when a reason is "feedback" or "delivered" or "vacation".
2. "softbounce" is 0 when a reason is "userunknown" or "hostunknown" or "hasmoved"
3. "softbounce" is 1 when a reason is others except "onhold" and "undefined".
4. When the value of "reason" is "onhold" or "undefined", "softbounce" is decided by "deliverystatus", "replycode", and "diagnosticcode".

**Comment by azumakuniyuki** [comment]
This improvements were included v4.18.0 and released. 
@Quickeneen, Thank you so much !

**Comment by Quickeneen** [comment]
Thanks ! as soon as i can, i check this.

regards
