### ISSUE TITLE
reason filter

### ISSUE THREAD

**Issue by Quickeneen** [sisimai/p5-sisimai#209]
Hi! 

i got some "reason" => "onhold" with "diagnosticcode":"No Account xxx@xxx here by that name. indimail (#5.1.5)"   and i would like to improve the filter. is existing a method?

Regards
Gilles

**Comment by azumakuniyuki** [comment]
Hello,

To improve the filter for the bounce message is updating error message patterns defined in [Sisimai::Reason::UserUnknown](https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai/Reason/UserUnknown.pm) as regular expressions.

The better way to improve the filter is to implement Sisimai::MTA::IndiMail if we can get other error message patterns of "indimail".

By the way, is "indimail" a software at http://www.indimail.org ?

Regards,
azumakuniyuki

**Comment by Quickeneen** [comment]
Thanks, 

yes, this is the software.
ok i have some fix to send you.

**Comment by azumakuniyuki** [comment]
There is no `5.1.5` in the source code of indimail
```
/usr/local/src/indimail-mta# find . -type f -exec grep -E '5[.]1[.]5' {} + | wc -l
0
```
