### ISSUE TITLE
UserUnknown reason clarification

### ISSUE THREAD

**Issue by racke** [sisimai/p5-Sisimai#221]
Got a bounce with the following SMTP answer (email obscured in the example):

`554 5.7.1 <nevairbe@example.com>:
    Recipient address rejected: Access denied`

This is classifed as `userunknown`, though the documentation of Sisimai::Reason::UserUnknown indicates only answers like:

`  <kijitora@example.co.jp>: host mx01.example.co.jp[192.0.2.8] said:
      550 5.1.1 Address rejected kijitora@example.co.jp (in reply to
      RCPT TO command)`

**Comment by azumakuniyuki** [comment]
Thanks for the report. Perhaps, we think, error message patterns in `lib/Sisimai/Reason/*` should be updated. Would you send ( or attach on this issue ) the email you received to us after replacing all the sensitive information such as a hostname, an IP address, or an email address.

Best regards.

**Comment by racke** [comment]
I tested it again with an obviously wrong address and I got the same answer. So the reason _userunknown_ appears to be correct.

[access-denied.zip](https://github.com/sisimai/p5-Sisimai/files/942008/access-denied.zip)

**Comment by azumakuniyuki** [comment]
@racke Code fixed. The reason of the email is classified as "securityerror".

Thank you, again.
