### ISSUE TITLE
Address parsing

### ISSUE THREAD

**Issue by SteveTheTechie** [sisimai/p5-Sisimai#227]
I really like what this module has to offer.  However, I am running into issues w/ the address parsing for addresser addresses.

"Toastmasters Club 987654321 on behalf of Joe Schmo, ACS/CL" \<server@toastmastersclubs.org\>

is getting parsed into ACS/CLserver@toastmastersclubs.org as the addresser address

I am the current code maintainer/updater for a volunteer based website system and list server used by over 11,000+ Toastmasters public speaking clubs worldwide.   We do a *lot* of email, and I would like to deploy this module to allow us to better handle bounces.

However, I have had to learn many lessons about email the hard way.  Address parsing/validation is one of those areas...

We regularly handle addresses in any one of the following formats on incoming emails (all fake addresses of course):

1. donaldduck@gmail.com (Donald Duck, ACS/CL)
2. "Mickey Mouse" \<agenda@toastmastersclubs.org\>
3. Minnie Mouse \<m.mouse@bigpond.com\>
4. "Toastmasters Club 987654321 on behalf of Admin" \<server@toastmastersclubs.org\>

I would want any email related module that we use to be able to handle any of these formats, including the first one that has the comma in the display name.

**Comment by azumakuniyuki** [comment]
Thanks for the report. This is a bug in Sisimai::Address module. We'll try to fix the problem.

**Comment by azumakuniyuki** [comment]
Almost methods of Sisimai::Address have been rewrote and `name` and `comment` accessors have implemented. The following code shows a sample for parsing each email address:

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use lib './lib';
use Sisimai::Address;

my $EmailAddrs = [
    'Toastmasters Club 987654321 on behalf of Joe Schmo, ACS/CL" <server@toastmastersclubs.org>',
    'donaldduck@gmail.com (Donald Duck, ACS/CL)',
    '"Mickey Mouse" <agenda@toastmastersclubs.org>',
    'Minnie Mouse <m.mouse@bigpond.com>',
    '"Toastmasters Club 987654321 on behalf of Admin" <server@toastmastersclubs.org>',
];

for my $e ( @$EmailAddrs ) {
    printf("Email = %s\n", $e);
    my $v = Sisimai::Address->find($e);
    my $a = Sisimai::Address->make($v->[0]);

    printf("  Sisimai::Address\n");
    printf("    ->address = %s\n", $a->address);
    printf("    ->name    = %s\n", $a->name);
    printf("    ->comment = %s\n", $a->comment);
}
```

Code above shows the following results:

```shell
Email = Toastmasters Club 987654321 on behalf of Joe Schmo, ACS/CL" <server@toastmastersclubs.org>
  Sisimai::Address
    ->address = server@toastmastersclubs.org
    ->name    = Toastmasters Club 987654321 on behalf of Joe Schmo, ACS/CL
    ->comment = 
Email = donaldduck@gmail.com (Donald Duck, ACS/CL)
  Sisimai::Address
    ->address = donaldduck@gmail.com
    ->name    = donaldduck@gmail.com
    ->comment = (Donald Duck, ACS/CL)
Email = "Mickey Mouse" <agenda@toastmastersclubs.org>
  Sisimai::Address
    ->address = agenda@toastmastersclubs.org
    ->name    = Mickey Mouse
    ->comment = 
Email = Minnie Mouse <m.mouse@bigpond.com>
  Sisimai::Address
    ->address = m.mouse@bigpond.com
    ->name    = Minnie Mouse
    ->comment = 
Email = "Toastmasters Club 987654321 on behalf of Admin" <server@toastmastersclubs.org>
  Sisimai::Address
    ->address = server@toastmastersclubs.org
    ->name    = Toastmasters Club 987654321 on behalf of Admin
    ->comment = 
```

New Sisimai::Address class is available at the master branch of p5-Sisimai. Would you try to run the new Sisimai::Address or code above ?

Thank you.

**Comment by SteveTheTechie** [comment]
I will give it a try when I get some time.  :-)
