### ISSUE TITLE
Feature Suggestion: Fetch Sender address

### ISSUE THREAD

**Issue by SteveTheTechie** [sisimai/p5-Sisimai#228]
It would be really helpful if you could fetch not just the From address as the addresser, but the Reply-To and/or Sender addresses, if they are available.  I do not see how this is currently possible w/ Sisimai.

We have a list server that takes recipient addresses in an incoming email and expands them to member email addresses.  Because of this, most all of our outgoing emails come from a consistent "server@toastmastersclubs.org" email address that members can white list, so fetching that as addresser is not much help to us.   We put the original sender email address (The From of the incoming email) in the Sender header and the Reply-To header, so being able to access those would give us the ability to forward bounces back to the sender of original incoming email to the list server.

**Comment by azumakuniyuki** [comment]
An addresser address is got from some headers according to order defined in https://github.com/sisimai/p5-Sisimai/blob/v4.21.1/lib/Sisimai/RFC5322.pm#L40-L43 and the address which was found first is set as the value of `addresser`.

As of present, we have no plan to implement new accessors at `Sisimai::Data` object such as `sender`, `reply-to` and no plan to update member variables of `Sisimai::Data->addresser`.

Then, we would like to make a suggestion for getting the value of`Sender` and/or `Reply-To` header using the call back feature implemented at Sisimai 4.19.0. The following code shows a sample for getting these headers.

```parse.pl
#!/usr/bin/env perl
use strict;
use warnings;
use Sisimai;
use Data::Dumper;

my $file = shift;
my $call = sub {
    my $argv = shift;
    my $data = { 'sender' => undef, 'replyto' => undef };

    $data->{'sender'} = $argv->{'headers'}->{'sender'} || '';
    $data->{'replyto'} = $argv->{'headers'}->{'reply-to'} || '';

    return $data;
};
my $p = Sisimai->make($file, 'hook' => $call, 'field' => ['Sender', 'Reply-To']);
warn Data::Dumper::Dumper $p;
```

Note that the code above works on Sisimai 4.20.2 or later (`field` key of the argument in `make()` method has been implemented at Sisimai 4.20.2).


The following command parses https://github.com/sisimai/set-of-emails/blob/master/maildir/bsd/rfc3464-07.eml .

```shell
% perl ./parse.pl ./rfc3464-07.eml
```

The command above returns the following results.
```json
$VAR1 = [
          bless( {
                   'smtpcommand' => '',
                   'subject' => 'Nyaaan',
                   'reason' => 'expired',
                   'replycode' => '',
                   'alias' => '',
                   'diagnosticcode' => '',
                   'feedbacktype' => '',
                   'deliverystatus' => '4.4.0',
                   'lhost' => 'mail.example.org',
                   'messageid' => '000000000000000@list.example.jp',
                   'timezoneoffset' => '+0000',
                   'catch' => {
                                'sender' => 'neko-list-owner@example.org',
                                'replyto' => ''
                              },
                   'listid' => 'neko-list.example.org',
                   'smtpagent' => 'RFC3464',
                   'recipient' => bless( {
                                           'address' => 'kijitora@example.net',
                                           'alias' => '',
                                           'verp' => '',
                                           'user' => 'kijitora',
                                           'host' => 'example.net'
                                         }, 'Sisimai::Address' ),
                   'softbounce' => 1,
                   'diagnostictype' => 'SMTP',
                   'rhost' => 'mx54.exmaple.com',
                   'senderdomain' => 'list.example.jp',
                   'token' => '2a4c580daf1c72734f561e1e6a0023958ded7189',
                   'timestamp' => bless( [
                                           45,
                                           34,
                                           8,
                                           30,
                                           3,
                                           104,
                                           5,
                                           120,
                                           0,
                                           1083281685,
                                           1
                                         ], 'Sisimai::Time' ),
                   'addresser' => bless( {
                                           'address' => 'shironeko@list.example.jp',
                                           'verp' => '',
                                           'alias' => '',
                                           'host' => 'list.example.jp',
                                           'user' => 'shironeko'
                                         }, 'Sisimai::Address' ),
                   'action' => 'delayed',
                   'destination' => 'example.net'
                 }, 'Sisimai::Data' )
        ];
```

The value of `Sender` is in the value of `catch` accessor.
Description about the callback feature is available at http://libsisimai.org/en/usage/#callback .

Best regards.

**Comment by SteveTheTechie** [comment]
Wow!  Thank you very much for your extensive reply!  I had not yet looked into the callback and catch features, so I will definitely look into that.

**Comment by SteveTheTechie** [comment]
Ok, not exactly what I was expecting...    I got your hook/catch method working.  However, that will not meet my needs as it appears that it will only fetch top-level headers, and not the embedded headers from the MIME part w/  `**Content-Type:** message/rfc822`  which are the headers from the **original email** that triggered the bounce back.  I need the Sender and Reply-To from _those embedded headers_, so I know who to send my bounce message back to if the bounce analysed by Sisimai results in reason = userunknown.  Keep in mind that this is for a list server.

Is there any way to use Sisimai to get at those embedded headers, or is that just too far beyond its capabilities?

**Comment by azumakuniyuki** [comment]
Sorry, I was misunderstanding your needs.
The following code shows an example for getting some strings from the message body.

```perl
#!/usr/bin/env perl
use strict;
use warnings;
use Sisimai;
use Data::Dumper;

my $file = shift;
my $call = sub {
    my $argv = shift;
    my $data = { 'sender' => undef, 'errorsto' => undef };

    if( $argv->{'message'} =~ m/^Sender:[ ](.+)$/m ) {
        # Sender: header
        $data->{'sender'} = $1;
    }
    $data->{'errorsto'} = $1 if $argv->{'message'} =~ m/^Errors-To:\s*(.+)$/m;

    return $data;
};
my $p = Sisimai->make($file, 'hook' => $call, 'field' => ['Sender', 'Reply-To']);
warn Data::Dumper::Dumper $p;
```

Would you try to refer `message` key of `$argv` at the callback sub routine ? The `message` keeps entire message body and capturing codes above get and return the values you needed.

Best regards.

**Comment by SteveTheTechie** [comment]
Thanks! I will give this a try.

**Comment by SteveTheTechie** [comment]
Ok, that worked as expected.  Thanks! 

You may want to fix your comment above as the hook sub{} references 'Errors-To' but the Field argument references 'Reply-To'.   It may cause confusion for others reading this in the future.

**Comment by azumakuniyuki** [comment]
I appreciate your letting us know about the field name and sorry for the sample code in the previous comment was wrong. The `field` argument is only required for parsing headers of the email message at a callback sub routine.

When you write a code for getting some string from the message body only, `field` argument in `Sisimai->make()` method is not required like the following code:

```
my $p = Sisimai->make($file, 'hook' => $call);
```

Best regards.
