### ISSUE TITLE
Wrong reason for GoDaddy/secureserver.net diagnostic code; 5.1.1 too generic?

### ISSUE THREAD

**Issue by ViktorNacht** [sisimai/p5-Sisimai#236]
This is an issue and also a request for help contributing to your project.

Given the following diagnostic code...

`  <foobar@example.com>: host smtp.secureserver.net[72.167.238.29] said: 550
    5.1.1 <foobar@example.com>  - 192.0.2.0 has sent to too many
    recipients this hour. IB607  <http://x.co/rlbounce> (in reply to RCPT TO
    command)
`
... Sisimai categorizes the bounce as userunknown when it should be toomanyconn.

I've forked Sisimai and created a local branch with the proper pattern in Sisimai::Reason::TooManyConn to match as toomanyconn. Unfortunately, as long as Sisimai groks the status code as 5.1.1, the bounce is still designated userunknown. Once you edit the bounce and change the status code to anything other than 5.1.1, it finally matches as toomanyconn.

In general, I would argue that simply designating all 5.1.1 bounces to userunknown is too aggressive and leads to false positives. 

Specifically, I'd like to solve this issue by contributing to the project. I would appreciate any hints you have on how I can make sure my pattern is applied without defaulting to userunknown. 

I process about 100,000 bounces a day, and I have a number of patterns from onHold and other false positives that I'd like to add to the project once I better understand how it works.

**Comment by azumakuniyuki** [comment]
Thanks for the report and your contributing !

## Status: 5.1.1
RFC3464 says that "X.1.1" means `Bad destination mailbox address` at the following link:
https://tools.ietf.org/html/rfc3463

however, some MTAs or email services returns a error message which is not `userunknown` with status code "5.1.1". For example, the value of `reason` of [email-postfix-01.eml](https://github.com/sisimai/set-of-emails/blob/master/maildir/bsd/email-postfix-01.eml) is `5.1.1` but the value of `deliverystatus` is `5.1.1`.
[email-mailfoundry-02.eml](https://github.com/sisimai/set-of-emails/blob/master/maildir/bsd/email-mailfoundry-02.eml) is also the same.

Modules in `lib/Sisimai/Bite/Email` directory exist to select a correct bounce reason with parsing these bounce messages (and status codes) above.

## To resolve the issue
I think, it may be a bit difficult to resolve the issue by improvements in `Sisimai::Reason::UserUnknown`. Perhaps, Sisimai::Bite::Email::GoDaddy (or other suitable name) might be implemented.

## Sample email
Would you post the entire email message (including email headers) bounced from GoDaddy at this issue after substituting secret information (a local part, a hostname, and IP addresses) with some safe string.

If you have many bounce emails  which reason is `onhold` or `undefined`, fork sisimai/set-of-emails repository and add these emails into [to-be-debugged-becase/*](https://github.com/sisimai/set-of-emails/tree/master/to-be-debugged-because) directory.

Best regards.

**Comment by ViktorNacht** [comment]
Here you go, hope this helps:

`
From MAILER-DAEMON  Tue Sep 19 12:00:02 2017
Return-Path: <>
X-Original-To: postmaster@sender.com
Delivered-To: postmaster@sender.com
Received: from mx.sender.com (mx.sender.com [192.0.2.1])
	by mail.sender.com (Postfix) with ESMTP id 084521680B5A
	for <postmaster@sender.com>; Tue, 19 Sep 2017 12:00:02 -0700 (PDT)
Received: by mx.sender.com (Postfix)
	id F1F29402F2229; Tue, 19 Sep 2017 12:00:01 -0700 (PDT)
Date: Tue, 19 Sep 2017 12:00:01 -0700 (PDT)
From: MAILER-DAEMON@mx.sender.com (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: postmaster@sender.com
Auto-Submitted: auto-replied
MIME-Version: 1.0
Content-Type: multipart/report; report-type=delivery-status;
	boundary="DA209402F1B99.1505847601/mx.sender.com"
Content-Transfer-Encoding: 8bit
Message-Id: <20170919190001.F1F29402F2229@mx.sender.com>

This is a MIME-encapsulated message.

--DA209402F1B99.1505847601/mx.sender.com
Content-Description: Notification
Content-Type: text/plain; charset=us-ascii

This is the mail system at host mx.sender.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<original-recipient@example.com>: host smtp.secureserver.net[72.167.238.29] said: 550
    5.1.1 <original-recipient@example.com>  - 192.0.2.0 has sent to too many
    recipients this hour. IB607  <http://x.co/rlbounce> (in reply to RCPT TO
    command)

--DA209402F1B99.1505847601/mx.sender.com
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; mx.sender.com
X-Postfix-Queue-ID: DA209402F1B99
X-Postfix-Sender: rfc822; postmaster@sender.com
Arrival-Date: Tue, 19 Sep 2017 11:59:55 -0700 (PDT)

Final-Recipient: rfc822; original-recipient@example.com
Original-Recipient: rfc822;original-recipient@example.com
Action: failed
Status: 5.1.1
Remote-MTA: dns; smtp.secureserver.net
Diagnostic-Code: smtp; 550 5.1.1 <original-recipient@example.com>  - 192.0.2.1 has
    sent to too many recipients this hour. IB607  <http://x.co/rlbounce>

--DA209402F1B99.1505847601/mx.sender.com
Content-Description: Undelivered Message
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit

Return-Path: <postmaster@sender.com>
Received: from localhost.localdomain (mx1.sender.com [192.0.2.2])
	by mx.sender.com (Postfix) with ESMTP id DA209402F1B99
	for <original-recipient@example.com>; Tue, 19 Sep 2017 11:59:55 -0700 (PDT)
Content-Disposition: inline
Content-Transfer-Encoding: 8bit
Content-Type: text/html
MIME-Version: 1.0
X-Mailer: MIME::Lite 3.030 (F2.84; T2.13; A2.12; B3.13; Q3.13)
Date: Tue, 19 Sep 2017 11:59:55 -0700
X-Report-Abuse-To: abuse@fastemailflyers.com
From: "Original Sender" <original-sender@example.com>
To: "Original Recipient" <original-recipient@example.com>
Subject: Test

<html><body>Test</body></html>

--DA209402F1B99.1505847601/mx.sender.com--

`

Thanks!

V

**Comment by azumakuniyuki** [comment]
Thanks for the sample email, I'll try to implement code for fixing this problem.

**Comment by azumakuniyuki** [comment]
@ViktorNacht I've implemented `Sisimai::Rhost::GoDaddy` module and added 2 sample emails in `issue-236` branch by Pull-Request #237. Would you try to run `issue-236` branch and try to parse bounce mails from GoDaddy ?

**Comment by ViktorNacht** [comment]
@azumakuniyuki,

Thank you so much for working on this. This was much better, but it looks like GoDaddy domains can also receive emails at mailstore1.secureserver.net. For us, roughly 25% of these messages are from mailstore1, while the rest are from smtp.secureserver.net. Our logs don't show any additional hosts, but maybe wildcarding the host might be a good idea.

`<original-recipient@example.com>: host mailstore1.secureserver.net[68.178.213.244] said:
    550 5.1.1 <original-recipient@example.com>  - 192.0.2.1 has sent to too many
    recipients this hour. IB607  <http://x.co/rlbounce> (in reply to RCPT TO
    command)
`

I can send you a complete bounce if you need it.

Also, there is a new variation of this error message:

`host smtp.secureserver.net[68.178.213.203] said: 550 5.1.0 <192.0.2.1> This IP has sent too many messages this hour. IB504 <http://x.co/rlbounce> (in reply to MAIL FROM command)`

Again, if you need a full bounce, let me know.

Finally, do you know of any existing script that can anonymize bounces in bulk?

Thanks!

**Comment by azumakuniyuki** [comment]
@ViktorNacht Thank you for telling me about the another mail host name. I've added `mailstore1` into Sisimai::Rhost class as a regular expression like `(?:smtp|mailstore)[.]secureserver[.]net`. When another host of sercureserver.net appeared, I will replace the first part of keys in `$RhostClass` with wildcard.

And other error codes beginning with `IB` are also defined in Sisimai::Rhost::GoDaddy https://github.com/sisimai/p5-Sisimai/blob/cec1da6a9a5795b4768cf0a34f88d3cc50eae91f/lib/Sisimai/Rhost/GoDaddy.pm#L6-L30 . Error codes and messages are picked from https://www.godaddy.com/help/what-does-my-email-bounceback-mean-3568 . If you have any bounce message which error code is not found at the URL above, please tell me the code and messages.

And then, I have a plan to implement an anonymizing tool but it has not been completed yet...

Thanks for testing again :-)

**Comment by ViktorNacht** [comment]
This worked great! What a wonderfully comprehensive solution. Thank you.

**Comment by azumakuniyuki** [comment]
Thanks for testing :-) I'll merge the branch to master.
