### ISSUE TITLE
SMTP error codes in laposte.net

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/p5-Sisimai#241]
Some error codes reported at issue #239.

# LPN***_***
- [ ] LPN003_109
```
5.5.0 Service refusé; Veuillez essayer plus tard.service refused.please try later LPN003_109
```

- [x] LPN00[47]_401 `blocked`
```
550 5.5.0 SPF: 80.12.242.126 is not allowed to send mail. LPN004_401
```

- [ ] LPN00[467]_420 `suspend`
```
550 550 5.1.1 Boite du destinataire archivee. Archived recipient. LPN004_420 [420] 

Boite du destinataire archivee. Archived recipient. LPN007 420
(in reply to RCPT TO command)
```

- [ ] LPN004_510
```
5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN004_510
```

- [X] LPN007_510 `blocked`
```
550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN007_510.
```

- [ ] LPN104-105
```
Une erreur est survenue lors de l'envoi du message. Le serveur a répondu '4.2.1 service refusé'. Veuillez essayer plus tard. LPN 104-105"
```

- [ ] LPN104_424
```
4.2.1 Service refuse.
Veuillez essayer plus tard. Service refused, please try later. LPN104_424. Veuillez vérifier le message et essayer à nouveau.
```

- [ ] LPN105_510
```
550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN105_510
```

- [x] LPN416 `userunknown`
```
550 5.1.1 Adresse d au moins un destinataire invalide. Invalid recipient. LPN416 416
```

**Comment by azumakuniyuki** [comment]
This issue has been moved to #243

**Comment by sharoilo** [comment]
@azumakuniyuki did u find any solution to this problem??

**Comment by azumakuniyuki** [comment]
@sharoilo Hello,
As of v4.22.3, we've implemented https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai/Rhost/FrancePTT.pm to resolve this issue and #243.

However, error code table in #243 don't cover all the error codes of Orance, La Poste, and Freeserve.
If you know any error code listed in the table, please tell us details.

Thanks.

**Comment by sharoilo** [comment]
@azumakuniyuki SMTP protocol failure: Unexpected reply code to RSET command; 421 4.7.0 lpn-prd-vrin012 Error: too many errors by smtpz4.laposte.net (194.117.213.1) while connected from

**Comment by azumakuniyuki** [comment]
@sharoilo Thanks for the error message. We want to test and make sure the parsed results so would you post the entire bounce mail message including all the headers to this issue ?

**Comment by sharoilo** [comment]
the errors below are they resolved or still , when i try to send email to my laposte client i cant sent a lot because my message content always got bounced why is that ??

**Comment by sharoilo** [comment]
Error: "550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN006_510" while connected from
--

**Comment by azumakuniyuki** [comment]
We need the entire bounce mail message (including all the headers) to inspect an error reason.
Best regards.

**Comment by sdesrousseaux** [comment]
Bonjour
Je rencontre une erreur depuis ce matin. Je travaille pour un site internet de vente en ligne et les emails envoyés à un de nos clients de la poste sont rejetés.
Dans les log du serveur j'ai ceci : 

`Nov 7 05:01:00 srv6 postfix/smtp19050: A5E171423C0: to=<XXX@laposte.net>, relay=smtpz4.laposte.net[194.117.213.1]:25, delay=57, delays=0/28/25/3.1, dsn=5.5.0, status=bounced (host smtpz4.laposte.net[194.117.213.1] said: 550 5.5.0 Service refuse. Veuillez essayer plus tard. service refused, please try later. LPN006_510 (in reply to end of DATA command))`

Je ne suis pas admin serveur et je ne sais pas comment corriger ce problème.
Le emails partent par une fonction mail() de php
