### ISSUE TITLE
SMTP Error Codes on Orange, La Poste and other ESPs in France

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/p5-Sisimai#243]
Follow-up issue #240 and #241 and pull-request #239 

SMTP error codes of orange.fr and laposte.net seem to the same  (using the same email system ?)
Error code format is the followings:

* orange.fr: OFR_*** or OFR***_***
* laposte.net: LPR_***
* freeserve.com: OUK***

| Code | Message                                              | Reason         | OFR | LPN | OUK |
|------|------------------------------------------------------|----------------|-----|-----|-----|
| 103  | Service refuse. Veuillez essayer plus tard           | blocked        | ok  |     |     |
| 104  | Trop de connexions, veuillez verifier votre ...      | toomanyconn    | ok  | ok  |     |
| 105  | service refusé. Veuillez essayer plus tard.         | ?              |     | ok  |     |
| 109  | Service refusé; Veuillez essayer plus tard.         | ?              |     | ok  |     |
| 201  | Service refusé; Veuillez essayer plus tard.         | ?              | ok  |     |     |
| 302  | service refused, please try later. LPN105_302        | ?              |     | ok  |     |
| 305  | 550 5.7.0 Code d'authentification invalide OFR 305   | securityerror  | ok  |     |     |
| 401  | SPF: *** is not allowed to send mail. LPN004_401     | blocked        |     | ok  |     |
| 402  | Authentification requise.                            | securityerror  | ok  | ok  |     |
| 403  | Emetteur invalide. Invalid Sender.                   | rejected       |     | ok  |     |
| 405  | Emetteur invalide. Invalid Sender.                   | rejected       | ok  | ok  | ok  |
| 415  | Emetteur invalide. Invalid Sender. OFR_415           | rejected       | ok  | ok  |     |
| 416  | Adresse d au moins un destinataire invalide          | userunknown    | ok  | ok  |     |
| 417  | Boite du destinataire pleine                         | mailboxfull    | ok  | ok  |     |
| 418  | Adresse d au moins un destinataire invalide          | userunknown    | ok  |     |     |
| 420  | Boite du destinataire archivee. Archived recipient.  | suspend        |     | ok  |     |
| 421  | 5.5.3 Mail from not owned by user. LPN105_421.       | rejected       |     | ok  |     |
| 423  | Service refused, please try later. LPN105_423        | ?              |     | ok  |     |
| 424  | Veuillez vérifier le message et essayer à nouveau  | ?              |     | ok  |     |
| 506  | Mail rejete. Mail rejected. OFR_506 [506]            | spamdetected   | ok  |     |     |
| 510  | Service refuse. Veuillez essayer plus tard.          | blocked        |     | ok  |     |
| 513  | Mail rejete. Mail rejected. ofr_513 [513]            | ?              | ok  |     | ok  |
| 514  | Taille limite du message atteinte                    | mesgtoobig     | ok  | ok  |     |

**Comment by azumakuniyuki** [comment]
```
La Poste manages a webmail , with addresses ending with @ laposte.net, based on Zimbra.
```
https://fr.wikipedia.org/wiki/La_Poste_(entreprise_fran%C3%A7aise)

**Comment by azumakuniyuki** [comment]
Code 506 (OFR_506) seems to be a `spamdetected`.
```
Thibautviv répondu le  décembre 22, 2014
J'ai enfin trouvé LA solution :

le probleme venait de ma signature, celle ci comprenait le lien qui re dirigeait vers la présentation de ma societe et ceci était perçu comme un spam par certain serveurs.


merci de votre aide
```
https://answers.microsoft.com/fr-fr/outlook_com/forum/oemail-osend/impossible-denvoyer-mail-vers-orange-et-wanadoo/50874212-8704-499a-aa2c-c123035e79c6?auth=1

**Comment by azumakuniyuki** [comment]
Code 103 (OFR_103) is `blocked`.
```
Here is the answer Orange Internet Service Abuse  to a user who posted on abuse@wanadoo.fr  :
Hello, 
A number of Gmail IP addresses have been temporarily blocked (until the end of the day) following their use in sending a phishing campaign spoofing our identity. 
This blockage will be lifted automatically around 18:00. 
Regards 
Service Abuse Orange Internet
```
https://communaute.orange.fr/t5/mon-mail-Orange/Emails-bloqu%C3%A9s-par-Orange/m-p/179201#M7536

**Comment by Quickeneen** [comment]
Hi, you can add also free.fr , one of the most ESP in france.
http://postmaster.free.fr, you will able to find error code on this page. 

let me collect more information about other ESP in france. i will let you know soon :)

**Comment by azumakuniyuki** [comment]
@Quickeneen Hello, Thanks for the advice ! I'll implement error codes and messages of free.fr at another branch. Then I'm waiting for other information about ESPs in France.

Thank you :-)

**Comment by Quickeneen** [comment]
@azumakuniyuki , SFR is another one, you can find all details about smtp codes here
http://www.delivernow.eu/en/tag/sfr-en

With Orange, Laposte, Free and SFR, you have everything for france :)

**Comment by azumakuniyuki** [comment]
@Quickeneen Thanks for the information about SFR ! I've found error codes and domains at the page. I'm glad to implement codes for support many ESPs in France :-)

Thank you,
