### ISSUE TITLE
New email with another one as attachment is considered as bounce

### ISSUE THREAD

**Issue by whity** [sisimai/p5-Sisimai#296]
Hello,

Found an issue that seems like a bug.
Having an email with other email as attachment, the sisimai is considering it as a bounce.
Could you please take look, thanks.

[email.txt](https://github.com/sisimai/p5-Sisimai/files/2564010/email.txt)
[perl-dump.txt](https://github.com/sisimai/p5-Sisimai/files/2564003/perl-dump.txt)

**Comment by azumakuniyuki** [comment]
Hello,

Thanks for the report. I've confirmed that sisimai detects the email as a bounce. It may be a bug in Sisimai::RFC3464 class.

Thanks :-)

**Comment by whity** [comment]
Hi @azumakuniyuki , many thanks for the quick fix.

**Comment by azumakuniyuki** [comment]
@whity Hello, I've fixed this bug and registered the email you attached above as set-of-emails/maildir/not/is-not-bounce-02.eml for using `make test` at p5-Sisimai, rb-Sisimai, and set-of-emails repository.

Thanks :-)

**Comment by azumakuniyuki** [comment]
Fixed code is included `v4.24.0p1` tag: https://github.com/sisimai/p5-Sisimai/releases/tag/v4.24.0p1

**Comment by whity** [comment]
Hi @azumakuniyuki , just a quick question.
There will be a patch release, e.g. 'v4.24.1'?

Thank you.

**Comment by azumakuniyuki** [comment]
@whity We've released v4.24.1 just now :-)

**Comment by whity** [comment]
@azumakuniyuki cool , thanks.
