### ISSUE TITLE
Error encountered

### ISSUE THREAD

**Issue by beeing** [sisimai/p5-Sisimai#310]
Running the below:

```
perl -MSisimai -lE 'print Sisimai->dump(shift)' ./messages/ > report.json
```

causes the below error to be printed:

Can't use an undefined value as an ARRAY reference at /Library/Perl/5.18/Sisimai/Rhost/GoogleApps.pm line 116.

And the email files in the directory is downloaded from outlook.com not google, perhaps this is the cause?

Thanks in advance.

**Comment by azumakuniyuki** [comment]
@beeing Thanks for the bug report. We have tried to fix the bug and it may be fixed at the current `master` branch.

`Sisimai::Rhost::GoogleApps` is called from `Sisimai::Rhost` only when the value of `rhost` in the parsed results is `aspmx.l.google.com`.  A bounce mail which causes the error may be sent from outlook.com to Google.

**Comment by azumakuniyuki** [comment]
@beeing If possible, could you show the entire email which causes the error at your private gist because we need a sample email for testing the bug and fixed code. The following command is helpful to find the email.

```shell
$ for v in $(find ./messages -type f); do
echo $v
perl -MSisimai -lE 'print Sisimai->dump(shift)' $v > /dev/null
done
```

Thanks

**Comment by beeing** [comment]
I found the problematic email, can you provide an email that I can send to?

**Comment by beeing** [comment]
Also, how do I update the fixes from master branch? Do I clone and run make again?

**Comment by azumakuniyuki** [comment]
> I found the problematic email, can you provide an email that I can send to?

`sisimai@cubicroot.jp` is our development team's email address. 

> Also, how do I update the fixes from master branch? Do I clone and run make again?

Yes, To update to the latest `master` is clone and install like the following commands:
```
$ git clone https://github.com/sisimai/p5-Sisimai.git
Cloning into 'p5-Sisimai'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 22880 (delta 14), reused 27 (delta 10), pack-reused 22837
Receiving objects: 100% (22880/22880), 7.56 MiB | 4.24 MiB/s, done.
Resolving deltas: 100% (15503/15503), done.

$ cd ./p5-Sisimai
$ make install-from-local
...
```

Or `-I./lib` option is useful to test the fixed version like the following:

```
$ git clone https://github.com/sisimai/p5-Sisimai.git
...
$ cd ./p5-Sisimai
$ perl -I./lib -MSisimai -lE 'print Sisimai->dump(shift)' ./path/to/messages-directory
```

**Comment by azumakuniyuki** [comment]
@beeing We have received a email with the bounce mail as a sample. We are going to inspect the bug tomorrow, thanks :-)

**Comment by beeing** [comment]
Thanks @azumakuniyuki

**Comment by azumakuniyuki** [comment]
@beeing We have improved code at `Sisimai::Bite::Email::Exim` module based on the bounce mail you gave. The parsed results generated by the current `master` branch are the following:

```
- reason: "userunknown"
- deliverystatus: "5.1.1"
- smtpagent: "Email::Exim"
```

Thanks :-)

**Comment by beeing** [comment]
Great! Thank you for the quick fix.
