### ISSUE TITLE
Empty manpages

### ISSUE THREAD

**Issue by guimard** [sisimai/p5-Sisimai#344]
Hi,

Perl install generates 2 empty manpages: Sisimai::Bite::Email and Sisimai::Bite::JSON. I didn't find why.

Cheers,
Xavier

**Comment by azumakuniyuki** [comment]
Hello, We had forgotten to write POD section at these modules because modules in Sisimai::Bite will be removed at the next release of Sisimai (v4.25.5). We will write POD section within a few days and add tag `v4.25.4p1` into the fixed code.

Best regards.

**Comment by azumakuniyuki** [comment]
@guimard Hello, we have created new tag `v4.25.4p1` at https://github.com/sisimai/p5-Sisimai/releases/tag/v4.25.4p1 including the fix for this issue.

**Comment by guimard** [comment]
Hi,

I patched Debian package, so I can wait for next stable release. Many thanks !

**Comment by azumakuniyuki** [comment]
@guimard  Thanks for the patched package.  We're planning that the next release (v4.25.5) on 22 Jan.

**Comment by azumakuniyuki** [comment]
@guimard We have released v4.25.5 yesterday :-)

**Comment by guimard** [comment]
@azumakuniyuki , uploaded with a little spelling patch, thanks !
