### ISSUE TITLE
apple me.com/mac.com/icloud.com vacation bounce (not RFC standard)

### ISSUE THREAD

**Issue by aderumier** [sisimai/p5-Sisimai#346]
Hi,
I'm seeing some vacation bounce coming from apple (me.com , mac.com),
They don't use any RFC standard, but have specific headers

```
Return-Path: <xxx@mac.com>
X-Original-To: xxxx@originalfromdomain.com
From: xxx@mac.com
To: xxxx@originalfromdomain.com
Subject: xxxx
Date: Mon, 16 Dec 2019 10:20:53 +0000
Message-id: <30a87ac7-16dc-4b7c-bf82-3a5c6f784ff8-vac@icloud.com>
In-Reply-To: <xxxx@originalfromdomain.com>
References: <xxxx@originalfromdomain.com>
X-Apple-Criteria: {kind=VACATION,recipients=1396}
X-Apple-Action: VACATION
X-Apple-UUID: 30a87ac7-16dc-4b7c-bf82-3a5c6f784ff8
X-Apple-Server: st13p27ic-ztba19270301 mailgateway 1923B114
Content-type: text/plain; charset=UTF-8
 ```

I don't known if it's something that could be parsed by sisimai ?

**Comment by azumakuniyuki** [comment]
As of present, the latest version of Sisimai can not parse such email above. However, to implement some code for detecting `X-Apple-Action: VACATION` or `Subject: Auto reply: ...` at `lib/Sisimai/RFC3834.pm` may make sisimai can parse.
