### ISSUE TITLE
Dump to JSON with large directories

### ISSUE THREAD

**Issue by japettyjohn** [sisimai/p5-sisimai#379]
The dump to JSON one liner is very convenient but difficult to use with large message counts. An option to to dump to JSON Lines would obviate the obvious memory pressure which comes with keeping a giant array of bounces in memory.

**Comment by azumakuniyuki** [comment]
Sisimai may not be able to parse a directory including a large number of emails at one time. The better ways are the followings:

- Split the directory into several directories including less than 10000 (or fewer) emails and parse per directory.
- Create a script for parsing 10000 (or fewer) emails at a time. The code https://github.com/sisimai/p5-Sisimai/blob/master/lib/Sisimai.pm#L30-L44 may be helpful.

Best regards
