### ISSUE TITLE
Error parsing From address from Feedbackloop

### ISSUE THREAD

**Issue by jcbf** [sisimai/p5-Sisimai#385]
I was testing Sisimai with a set of feedback loop messages and noticed that Multi line From addresses with a @  would break parsing.

To reproduce I downloaded  arf-22.eml file from repo and changed the from `Address`

> perl -MSisimai -e 'print Sisimai->dump("arf-22.eml.");'  | jq '.[].addresser'

"sironeko@example.com"

Then changed the From address

```
--- arf-22.eml.1	2020-03-31 19:41:41.056614734 +0000
+++ arf-22.eml	2020-03-31 19:41:54.292589247 +0000
@@ -36,7 +36,8 @@
     Thu, 29 Apr 2016 23:34:45 +0000
 Date: Thu, 29 Apr 2016 23:34:45 +0200
 To: kijitora@example.com
-From: Neko <sironeko@example.com>
+From: ass@as
+ <sironeko@example.com>
 Subject: Nyaan
 MIME-Version: 1.0
 Content-Transfer-Encoding: 8bit
```

> perl -MSisimai -e 'print Sisimai->dump("arf-22.eml.");'  | jq '.[].addresser'

"ass@as"

**Comment by azumakuniyuki** [comment]
@jcbf Hello, Thanks for the bug report. We have created the same email and tested it. Then, the DDP module shows the following results:

```
            addresser        Sisimai::Address  {
                internals: {
                    address   "ass@as",
                    alias     "",
                    comment   "",
                    host      "as",
                    name      "ass@as",
                    user      "ass",
                    verp      ""
                }
            },
```

Perhaps, this is a bug in `Sisimai::Address->find` method...

**Comment by azumakuniyuki** [comment]
@jcbf We have fixed and tagged with `v4.25.5p11` :-)

**Comment by jcbf** [comment]
Good, I'll be parsing some DSN regularly and give feedback.

Is there any simple way just to parse the response from the remote server?
example:

> 550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient not found by SMTP address lookup (in reply to RCPT TO command))

**Comment by azumakuniyuki** [comment]
There is no simple way to parse the response because of many formats of error messages, modules in Sisimai::Lhost::* is needed to get the response. However, when the response exists in any scalar value, the following sample may help you:

```
#!/usr/bin/env perl
use strict;
use warnings;
use Sisimai;
use Sisimai::SMTP::Reply;
use Sisimai::SMTP::Status;

my $e = '550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient not found by SMTP address lookup (in reply to RCPT TO command))';
printf("%s\n", Sisimai::SMTP::Status->find($e));    # 5.1.10
printf("%s\n", Sisimai::SMTP::Reply->find($e));     # 550
printf("%s\n", Sisimai->match($e));                 # userunkonwn
```
