### ISSUE TITLE
Sisimai::Rhost::Cox

### ISSUE THREAD

**Issue by azumakuniyuki** [sisimai/p5-sisimai#398]
- Cox using `AUP#CODE` format in their error codes https://www.cox.com/residential/support/email-error-codes.html
- We've implemented `Sisimai::Rhost::Spectrum` to parse `AUP#nnn` error codes
- However, we have no sample email returned from cox.com

**Comment by meir-w** [comment]
I have a file with Cox feedback - attached.
[cox_bounce.txt](https://github.com/sisimai/p5-sisimai/files/4890556/cox_bounce.txt)

**Comment by azumakuniyuki** [comment]
@meir-w Thanks for the sample email :-) We will implement `Sisimai::Rhost::Cox` based on the sample email for a few days.
By the way, Would you allow us to register `cox_bounce.txt` into `./set-of-emails/maildir/bsd` as a public sample?

**Comment by meir-w** [comment]
Sure.
Let me know if you need any other US domains.

**Comment by azumakuniyuki** [comment]
@meir-w We have implemented `Sisimai::Rhost::Cox` and registered an email gave you as `rhost-cox-01.eml`
