### ISSUE TITLE
Many userunknown strings parsed as softbounce

### ISSUE THREAD

**Issue by hege-li** [sisimai/p5-sisimai#409]
Here's a bunch of common diagnosticcode strings from my logs, that are mistakenly parsed as softbounces. I'll see if I can figure out how to patch these.

```
550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient not found by SMTP address lookup

5.1.0 - Unknown address error 550-'5.1.1 Mailbox <xxx.xxx@xxx.xxx> does not exist' (delivery attempts: 0)

5.1.0 - Unknown address error 550-'5.1.1 <xxx.xxx@xxx.xxx>... User unknown' (delivery attempts: 0)

5.1.0 - Unknown address error 550-'5.1.1 <xxx.xxx@xxx.xxx>: Recipient address rejected: xxx.xxx' (delivery attempts: 0)
```

**Comment by hekeli** [comment]
I see many of these do have correct reason "userunknown", but why are they marked as softbounce: 1 then?

**Comment by azumakuniyuki** [comment]
@hekeli Thanks for the report. Almost all of these values of `diagnosticcode` above should be `softbounce=0`. We will try to parse if you post some bounce mails including all the email headers as a sample to us.

**Comment by hekeli** [comment]
I haven't saved the original messages, but I will start saving new ones. But there's clearly some logic bug somewhere if reason == "unknownuser" and action == "failed", yet softbounce stays.

**Comment by azumakuniyuki** [comment]
Thank you :-) I'm waiting for you to post bounce mails as a  sample.

**Comment by hekeli** [comment]
Very sorry I made embarassing mistake grepping with "jq" tool. I've updated first post with correct diagnosticcode strings. We simply need to fix the reason to "unknownuser" for these. There is no other softbounce logic bug. :)
