### ISSUE TITLE
Localize global variables used by YAML and YAML::Syck

### ISSUE THREAD

**Issue by bschmalhofer** [sisimai/p5-sisimai#438]
Hi,

in https://metacpan.org/release/AKXLIX/Sisimai-v4.25.11/source/lib/Sisimai/Data/YAML.pm I noticed that the global package variables of YAML and YAML::Syck are set. The changed variables will have an effect outside of the sub `dump()`. I think it would be better to localize changes to these variables. This can be done by adding the `local` keyword in the relevant line. See also https://metacpan.org/dist/YAML/view/lib/YAML.pod#GLOBAL-OPTIONS .

Best regards,
    Bernhard

**Comment by azumakuniyuki** [comment]
hello, thanks for the report. I will check and test the code tomorrow :-)

**Comment by azumakuniyuki** [comment]
Merged into `master` and `4-stable`.
