### ISSUE TITLE
Provide method to move or remove processed files

### ISSUE THREAD

**Issue by deepvoice** [sisimai/p5-sisimai#462]
Enhancement request to provide a method to move or remove the processed files.

**Comment by azumakuniyuki** [comment]
We have no plan to implement the method you said, but the value of `origin` in the parsed result may helps you like the following command:

```shell
% perl -MSisimai -lE 'my $v = Sisimai->make(shift); for my $e ( @$v ){ unlink $e->origin }' /tmp/test-1.eml
```
