### ISSUE TITLE
RFC3834.pm checks for header 'x-auto-response-suppress'

### ISSUE THREAD

**Issue by whity** [sisimai/p5-sisimai#491]
Hello,

The module `RFC3834` is checking the header `x-auto-response-suppress` to detect if the message is an auto reply but, imho, this is not correct.
From what I could understand, this header is to actually prevent auto-replies messages to the sender, in exchange servers, and not to identify the message as an auto-reply.

references:
* https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxcmail/ced68690-498a-4567-9d14-5c01f974d8b1?redirectedfrom=MSDN (in the second table, column "Meaning", you can see always the term "Suppress")
* https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/
* https://ideas.salesforce.com/s/idea/a0B8W00000GdjicUAB/prevent-autoreplies-when-sending-outbound-email

btw, thanks for the awesome lib :)

thanks

**Comment by azumakuniyuki** [comment]
@whity Thank you for the advice regarding the `X-Auto-Reply-Suppress` header. I will review the code and fix it within a few days :-)
